name: Build GKI 5.10 (repo + Bazel)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y bc bison flex libssl-dev libelf-dev ccache python3 \
          zip unzip rsync curl jq file tar xz-utils zstd pkg-config libncurses-dev \
          repo git

    - name: Initialize repo
      run: |
        mkdir kernel
        cd kernel
        repo init -u https://android.googlesource.com/kernel/manifest -b common-android13-5.10

    - name: Sync repositories
      run: |
        cd kernel
        repo sync -c -j8 --no-tags --no-clone-bundle

    - name: Install Bazelisk
      run: |
        sudo wget -O /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/download/v1.19.0/bazelisk-linux-amd64
        sudo chmod +x /usr/local/bin/bazel

    - name: Build GKI kernel
      run: |
        cd kernel
        bazel build //common:kernel_aarch64

    - name: Upload Image
      uses: actions/upload-artifact@v4
      with:
        name: gki-image
        path: kernel/bazel-bin/common/kernel_aarch64/Image
