name: Build GKI 5.10 (Bazel)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout empty repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          bc bison flex libssl-dev libelf-dev ccache python3 \
          zip unzip rsync curl jq file tar xz-utils zstd pkg-config libncurses-dev

    - name: Install Bazelisk (Bazel wrapper)
      run: |
        sudo wget -O /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/download/v1.19.0/bazelisk-linux-amd64
        sudo chmod +x /usr/local/bin/bazel

    - name: Clone GKI kernel
      run: |
        git clone --depth=1 -b android13-5.10 https://android.googlesource.com/kernel/common kernel/common

    - name: Clone build system
      run: |
        git clone --depth=1 -b main-kernel-build-2023 https://android.googlesource.com/kernel/build kernel/build

    - name: Clone clang
      run: |
        git clone --depth=1 -b android13-release https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 kernel/prebuilts/clang

    - name: Clone build-tools
      run: |
        git clone --depth=1 -b android13-release https://android.googlesource.com/platform/prebuilts/build-tools kernel/prebuilts/build-tools

    - name: Build GKI kernel (Bazel)
      run: |
        cd kernel/build
        bazel build //common:kernel_aarch64

    - name: Upload Image
      uses: actions/upload-artifact@v4
      with:
        name: gki-image
        path: kernel/build/bazel-bin/common/kernel_aarch64/Image
